# Generated by Django 4.2.11 on 2024-05-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phonebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=30, unique=True, verbose_name="휴대폰 번호"),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name_plural": "휴대폰인증 관리 페이지",
                "db_table": "authentications",
            },
        ),
        migrations.CreateModel(
            name="SupportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_time", models.CharField(max_length=10)),
                ("status", models.CharField(default="pending", max_length=10)),
            ],
        ),
    ]
