# Generated by Django 4.2.13 on 2024-05-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_id', models.IntegerField()),
                ('groupselector', models.CharField(max_length=1)),
                ('speakerselector', models.CharField(max_length=1)),
                ('exchanger', models.CharField(max_length=1)),
                ('remoteamp', models.CharField(max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
